# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad60845e1c67f051c8e76ce0fbeccc2a0950c6b125704f878d20d6aca8c1afc417926c31733720bdc0d8647f76e810e3dfc3765fa5e8e14b73c3bf4925ee2e95

test:
  secret_key_base: 35cd5dea000ff245abf2acb96adfdb60731937ee2f975640950fe8b70cb73cbd395c20d5770dc636071cc93dd2b5f11c4ba89720a6e2dd4f5f68fe44b9bb8d24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
